language: go

env: GO111MODULE=on GOFLAGS='-mod vendor'

# Only clone the most recent commit.
git:
  depth: 1

install:
- eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=master b
- go mod download

script:
- make vet
- make test